# Generated by Django 2.2.3 on 2019-07-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_submitted',
            new_name='date',
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1),
        ),
    ]
