# Generated by Django 2.2.3 on 2019-07-21 15:29

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Детский'), (2, 'Средний')])),
                ('material', models.PositiveSmallIntegerField(choices=[(1, 'Кожзаменитель'), (2, 'Велюр')])),
                ('price', models.PositiveIntegerField()),
                ('popularity', models.SmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('length', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=4, unique=True)),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Красный'), (2, 'Зеленый'), (3, 'Синий'), (4, 'Желтый'), (5, 'Черный'), (6, 'Фиолетовый'), (7, 'Белый'), (8, 'Серый'), (9, 'Коричневый')])),
                ('color_photo', models.ImageField(upload_to=shop.models.color_photo_path)),
                ('small_photo', models.ImageField(upload_to=shop.models.small_photo_path)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Origin')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(editable=False, max_length=4, unique=True)),
                ('medium_photo', models.ImageField(upload_to=shop.models.medium_photo_path)),
                ('large_photo', models.ImageField(upload_to=shop.models.large_photo_path)),
                ('extralarge_photo', models.ImageField(upload_to=shop.models.extralarge_photo_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='origin',
            constraint=models.UniqueConstraint(fields=('name', 'size', 'material'), name='unique_name_size_material'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('origin', 'color'), name='unique_origin_color'),
        ),
    ]
