# Generated by Django 2.2.3 on 2019-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Красный'), (2, 'Зеленый'), (3, 'Синий'), (4, 'Желтый'), (5, 'Черный'), (6, 'Фиолетовый'), (7, 'White')]),
        ),
    ]
