# Generated by Django 2.2.3 on 2019-07-28 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190729_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Пожалуйста, введите номер телефона в формате 87001112233 или +77001112233', regex='^(8|(\\+7))\\d{10}$')]),
        ),
    ]
