# Generated by Django 2.2.3 on 2019-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190709_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paid'), (2, 'Packaged'), (3, 'Delivered'), (4, 'Exchanged'), (5, 'Returned'), (6, 'Canceled')], default=1),
        ),
    ]
