# Generated by Django 2.2.3 on 2019-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190711_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_id',
            field=models.CharField(default='', max_length=36),
        ),
    ]
