# Generated by Django 2.2.3 on 2019-08-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
