# Generated by Django 2.2.3 on 2019-07-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_to_pay',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
