# Generated by Django 2.2.3 on 2019-07-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_total_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_to_pay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
