# Generated by Django 2.2.3 on 2019-08-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190817_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='another_city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=128),
        ),
    ]
