# Generated by Django 2.2.3 on 2019-07-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190714_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Packaged'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Exchanged'), (5, 'Returned'), (6, 'Canceled')], default=1),
        ),
    ]
