# Generated by Django 2.2.3 on 2019-07-16 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190715_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Please enter a valid phone number. For example, 87001112233', regex='^8\\d{10}$')]),
        ),
    ]
