# Generated by Django 2.2.3 on 2019-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='another_city_chosen',
            field=models.BooleanField(default=False),
        ),
    ]
