# Generated by Django 2.2.3 on 2019-08-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_address_another_city_chosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='another_city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='another_city_chosen',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
