# Generated by Django 2.2.3 on 2019-08-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190819_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
